### ISSUE TITLE
Change to do to make it works in server

### ISSUE THREAD

**Issue by Aracaa** [Futuray-pgm/instruments_mcl#1]
I had to make adjustment to make it works in the "mineclone2 araca serveur"

* In all files, replace `instruments:` to `instruments_mcl:`
* Change the `harmonica_casing` recipe to use `mcl_core:gold_ingot` instead of `default:gold_ingot`
* Change the `drum_stick` recipe to replace dry_shrub by the mcl2 equivalent `mcl_core:deadbush`

**Comment by Futuray-pgm** [comment]
* **first point :** I don't know why an error is occurred on other minetest than my.
* **second and third point :** that are mistake made by me, I'll fix them.
Thanks !

**Comment by Aracaa** [comment]
Also, the receipe for `instruments:embouchure` has to be changed because it's the same as iron boot. In the server, I changed it like below, I had not better idea

```
minetest.register_craft({
		output = "instruments:embouchure",
		recipe = {
			{"", "", "mcl_core:iron_ingot"},
			{"mcl_core:iron_ingot", "", "mcl_core:iron_ingot"},
			{"mcl_core:iron_ingot", "", "mcl_core:iron_ingot"}
		}
	})```

**Comment by Futuray-pgm** [comment]
If you want, made a pull raquest or a commit!

**Comment by Aracaa** [comment]
I'll do a PR yes. maybe not today but during christmas holidays.

Also, we need to add group `handy = 1, pickaxey = 1` to drums element
